version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "5001:5001"
    restart: always
    volumes:
      - ./api:/app
    depends_on:
      - samdb
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=samdb

  samdb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: samdb
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3307:3307"
